version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hwdocker_postgres
    environment:
      POSTGRES_DB: hwdocker_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: .  # Используем корень проекта
      dockerfile: HWDocker/Dockerfile
    container_name: hwdocker_api
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=hwdocker_db;Username=user;Password=password
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
